spring:
  profiles:
    active: dev

---
spring:
  profiles: pro
  datasource:
    hikari:
     connection-test-query: select 1
     driver-class-name: com.mysql.jdbc.Driver
     jdbc-url: jdbc:h2:file:~/.h2/testdb
     username: root
     password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
scan:
  path: ['/home/vttmlin/IdeaProjects/ahjy/out/artifacts']

---

spring:
  profiles: dev
  datasource:
    hikari:
     connection-test-query: select 1
     driver-class-name: org.h2.Driver
     jdbc-url: jdbc:h2:file:~/.h2/testdb
     username: root
     password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
scan:
  path: ['/home/vttmlin/IdeaProjects/ahjy/out/artifacts/ahjy/WEB-INF']